spring.application.name=job-manager
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1

spring.datasource.username=SYSTEM

spring.datasource.password=monhan515

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true